server:
  port: 8080

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5432/bookshelf
    username: user
    password: password
     
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
      
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog.xml
    drop-first: true
      
logging:
  pattern:
    console: "%d{HH:mm:ss} %highlight(%-5level) %highlight(%48.48logger) - %msg%n"
  level:
    "[org.springframework.boot]": info
    "[org.hibernate.SQL]": debug
    
myapp:
  param1: 42
  param2: value
---

spring:
  config:
    activate:
      on-profile:
      - test

server:
  port: 8081


myapp:
  param1: 23
  param2: value2